version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0"

# docker-compose build
# docker-compose run app sh -c "django-admin startproject app ."
# docker-compose run app sh -c "python manage.py startapp core"
# docker-compose run app sh -c "python manage.py test && flake8"
